spring:
#  h2:
#    console:
#      path: /h2-console #Path at which the console is available,default:/h2-console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #default com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:h2:file:~/dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: dev
    password: dev
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000 # default 30s, ms
      pool-name: SimpleHikariCP # change hikari pool name,default HikariPool-1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

